services:

  postgres:
    image: postgres:16-alpine
    container_name: Techplanner_db

    environment:
      POSTGRES_DB: techplanner_pricing
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d techplanner_pricing"]
      interval: 5s
      timeout: 5s
      retries: 10

  component-service:
    image: juanfer28/component-service-app:latest

    ports:
      - "8083:8082"

    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JPA_DDL: ${JPA_DDL}

    depends_on:
      postgres:
        condition: service_healthy



  app:
    image: velez017/pricing-service-app:latest

    ports:
      - "8081:8081"
      - "8082:8082"

    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JPA_DDL: ${JPA_DDL}

    depends_on:
      postgres:
        condition: service_healthy


  quotation-service:
    image: techplanner-quotation-service:latest
    container_name: quotation-service

    ports:
      - "8080:8080"

    restart: always



volumes:
  pgdata:
